SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR amd64)

SET(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

SET(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)

SET(CMAKE_AR      ${TOOLCHAIN_PREFIX}-ar)
SET(CMAKE_AS      ${TOOLCHAIN_PREFIX}-as)
SET(CMAKE_LD      ${TOOLCHAIN_PREFIX}-ld)
SET(CMAKE_STRIP   ${TOOLCHAIN_PREFIX}-strip)
SET(CMAKE_RANLIB  ${TOOLCHAIN_PREFIX}-ranlib)
SET(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
SET(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
