SET(CMAKE_SYSTEM_NAME Termux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

SET(TOOLCHAIN_PREFIX i686-linux-android35)

SET(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-clang)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-clang++)

SET(CMAKE_AR      ${TOOLCHAIN_PREFIX}-ar)
SET(CMAKE_AS      ${TOOLCHAIN_PREFIX}-as)
SET(CMAKE_LD      ${TOOLCHAIN_PREFIX}-ld)
SET(CMAKE_STRIP   ${TOOLCHAIN_PREFIX}-strip)
SET(CMAKE_RANLIB  ${TOOLCHAIN_PREFIX}-ranlib)
SET(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
SET(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
SET(CMAKE_CXX_SCAN_FOR_MODULES OFF)
